// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohhyafgivjskqbwkepvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oaHlhZmdpdmpza3Fid2tlcHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTkxODYsImV4cCI6MjA2OTEzNTE4Nn0.YCOeSryhHjrpZEbaPiESsCI4f0TVmlA8JdLKPt5VQ4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});